name: Build Windows (AMD64)

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: windows-2019
            architecture: x86_64
            python: '3.8'
            inno_arch: x64compatible
            tools_architecture: x86_64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install build dependencies
        run: python -m pip install -e ".[build]"
      - name: Build with Nuitka
        shell: pwsh
        run: |
          $VERSION = python -c "from app.common.setting import VERSION; print(VERSION)"
          "VERSION=$VERSION" >> $env:GITHUB_ENV
          python deploy.py
      - name: Add aria2 tools
        shell: pwsh
        run: |
          $url = "https://github.com/XiaoshuDeXiaowo/GitHub-NetDisk-Tools/releases/download/v0.0.1/Windows-${{ matrix.tools_architecture }}.zip"
          Invoke-WebRequest -Uri $url -OutFile "$env:TEMP/tools.zip"
          Expand-Archive "$env:TEMP/tools.zip" "dist/GitHub-NetDisk.dist/tools" -Force
      - name: Install Inno Setup language
        shell: pwsh
        run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl" -OutFile "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl"
      - name: Build installer
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "/DMyAppVersion=$env:VERSION" "/DMyAppArch=${{ matrix.inno_arch }}" "/DMyArtifactArch=${{ matrix.architecture }}" GitHub-NetDisk.iss
      - uses: actions/upload-artifact@v4
        with:
          name: GitHub-NetDisk-v${{ env.VERSION }}-Windows-${{ matrix.architecture }}-Setup
          path: dist/GitHub-NetDisk-v${{ env.VERSION }}-Windows-${{ matrix.architecture }}-Setup.exe
